# Generated by Django 5.2.5 on 2025-08-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avarars', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tg_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Telegram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vk_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID ВКонтакте'),
        ),
    ]
