# Generated by Django 5.2.5 on 2025-09-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='appointment_date',
            field=models.DateTimeField(verbose_name='Дата и время записи'),
        ),
    ]
