# Generated by Django 5.2.5 on 2025-09-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timeslot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'Свободные окошки', 'verbose_name_plural': 'Свободные окошки'},
        ),
    ]
