# Generated by Django 5.2.5 on 2025-09-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_timeslot_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='date_time',
            field=models.DateTimeField(unique=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='Занято'),
        ),
    ]
